# Generated by Django 3.0.7 on 2020-06-18 12:44
import datetime

from django.db import migrations


def initial_db_base(apps, schema_editor):
    # We can't import models directly as they may be a newer
    # versions than this migration expects. We use the historical versions.
    AdvUser = apps.get_model('seance', 'AdvUser')
    Film = apps.get_model('seance', 'Film')
    Hall = apps.get_model('seance', 'Hall')
    Seance = apps.get_model('seance', 'Seance')
    SeanceBase = apps.get_model('seance', 'SeanceBase')
    Price = apps.get_model('seance', 'price')
    SeatCategory = apps.get_model('seance', 'SeatCategory')
    Seat = apps.get_model('seance', 'Seat')

    admin, _ = AdvUser.objects.get_or_create(username='initial_admin')

    film_bond = Film.objects.create(
        title='James Bond',
        starring='Daniel Craig and co',
        director='Somebody',
        duration=datetime.time(1, 40),
        description='A cool film about superman',
        admin=admin
    )

    film_365_days = Film.objects.create(
        title='365 Days',
        starring='Michele Morrone, Otar Saralidze',
        director='SMichele Morrone, Otar Saralidze',
        duration=datetime.time(1, 40),
        description='Interesting... Maybe))',
        admin=admin
    )

    seat_category = SeatCategory.objects.create(
        name='base',
        admin=admin
    )

    hall_yellow = Hall.objects.create(
        name='Yellow',
        quantity_seats=100,
        quantity_rows=10,
        description='Convenient place for your exciting journey',
        admin=admin
    )

    # create seats for hall
    for row in range(1, hall_yellow.quantity_rows + 1):
        for number in range(1, 11):
            Seat.objects.create(
                hall=hall_yellow,
                seat_category=seat_category,
                number=number,
                row=row
            )

    hall_red = Hall.objects.create(
        name='Red',
        quantity_seats=150,
        quantity_rows=10,
        description='Convenient place for your exciting journey... if you love many people in one place at a time)',
        admin=admin
    )

    for row in range(1, hall_red.quantity_rows + 1):
        for number in range(1, 16):
            Seat.objects.create(
                hall=hall_red,
                seat_category=seat_category,
                number=number,
                row=row
            )

    seance_base_bond = SeanceBase.objects.create(
        film=film_bond,
        hall=hall_yellow,
        date_starts=datetime.date.today(),
        date_ends=datetime.date.today() + datetime.timedelta(days=30),
    )

    seance_base_365 = SeanceBase.objects.create(
        film=film_365_days,
        hall=hall_red,
        date_starts=datetime.date.today(),
        date_ends=datetime.date.today() + datetime.timedelta(days=30),
    )

    seance_bond_noon = Seance.objects.create(
        time_starts=datetime.time(12, 0),
        time_ends=datetime.time(14, 00),
        description='For those who have long dinner time)',
        seance_base=seance_base_bond,
        admin=admin
    )

    seance_bond_evening = Seance.objects.create(
        time_starts=datetime.time(19, 0),
        time_ends=datetime.time(21, 0),
        description='For those who have time after work!)',
        seance_base=seance_base_bond,
        admin=admin
    )

    seance_bond_night = Seance.objects.create(
        time_starts=datetime.time(23, 50),
        time_ends=datetime.time(1, 30),
        description='For those who don\'t sleep at night!)',
        seance_base=seance_base_bond,
        admin=admin
    )

    seance_365_noon = Seance.objects.create(
        time_starts=datetime.time(12, 0),
        time_ends=datetime.time(15, 0),
        description='For those who have long dinner time)',
        seance_base=seance_base_365,
        admin=admin
    )

    seance_365_evening = Seance.objects.create(
        time_starts=datetime.time(19, 0),
        time_ends=datetime.time(21, 0),
        description='For those who have time after work!)',
        seance_base=seance_base_365,
        admin=admin
    )

    seance_365_night = Seance.objects.create(
        time_starts=datetime.time(23, 50),
        time_ends=datetime.time(1, 30),
        description='For those who don\'t sleep at night!)',
        seance_base=seance_base_365,
        admin=admin
    )

    price_bond_noon = Price.objects.create(
        seance=seance_bond_noon,
        seat_category=seat_category,
        price=100
    )

    price_bond_evening = Price.objects.create(
        seance=seance_bond_evening,
        seat_category=seat_category,
        price=180
    )

    price_bond_night = Price.objects.create(
        seance=seance_bond_night,
        seat_category=seat_category,
        price=120
    )

    price_365_noon = Price.objects.create(
        seance=seance_365_noon,
        seat_category=seat_category,
        price=120
    )

    price_365_evening = Price.objects.create(
        seance=seance_365_evening,
        seat_category=seat_category,
        price=200
    )

    price_365_night = Price.objects.create(
        seance=seance_365_night,
        seat_category=seat_category,
        price=150
    )


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_db_base)
    ]
