# Generated by Django 3.0.7 on 2020-06-18 08:15

from django.db import migrations


def init_base_price_list_and_seat_category(apps, schema_editor):
    # We can't import the PriceList and other models directly as they may be a newer
    # versions than this migration expects. We use the historical versions.
    AdvUser = apps.get_model('seance', 'AdvUser')
    admin, _ = AdvUser.objects.get_or_create(username='admin', password=1, is_superuser=True, is_staff=True)
    PriceList = apps.get_model('seance', 'PriceList')
    SeatCategory = apps.get_model('seance', 'SeatCategory')
    price_list = PriceList.objects.create(title='base price', price=100, admin=admin)
    SeatCategory.objects.create(name='base category', price_list=price_list, admin=admin)


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(init_base_price_list_and_seat_category),
    ]
