# Generated by Django 3.0.7 on 2020-06-18 08:10

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Film',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='title')),
                ('starring', models.CharField(max_length=200, verbose_name='starring')),
                ('director', models.CharField(max_length=100, verbose_name='director')),
                ('duration', models.TimeField(verbose_name='duration')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='instance created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='instance updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='in run?')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='instance created by')),
            ],
        ),
        migrations.CreateModel(
            name='Hall',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='name')),
                ('quantity_seats', models.PositiveSmallIntegerField(default=0, verbose_name='how many seats?')),
                ('quantity_rows', models.PositiveSmallIntegerField(default=0, verbose_name='how many rows?')),
                ('description', models.TextField(verbose_name='description')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='instance created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='instance updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='in run?')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='halls', to=settings.AUTH_USER_MODEL, verbose_name='instance created by')),
            ],
        ),
        migrations.CreateModel(
            name='PriceList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='title')),
                ('price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='price per one seat')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='instance created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='instance updated at')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seance_bases', to=settings.AUTH_USER_MODEL, verbose_name='instance created by')),
            ],
        ),
        migrations.CreateModel(
            name='Purchase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_price', models.DecimalField(decimal_places=2, max_digits=15, verbose_name='payed:')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='instance created at')),
                ('was_returned', models.BooleanField(default=False, verbose_name='was returned?')),
                ('returned_at', models.DateTimeField(blank=True, null=True, verbose_name='returned at')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='purchases', to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
        ),
        migrations.CreateModel(
            name='Seance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_starts', models.TimeField(verbose_name='starts at: ')),
                ('time_ends', models.TimeField(blank=True, null=True, verbose_name='ends at: ')),
                ('time_hall_free', models.TimeField(blank=True, null=True, verbose_name='ends at: ')),
                ('advertisements_duration', models.TimeField(default=datetime.time(0, 10), verbose_name='adds duration: ')),
                ('cleaning_duration', models.TimeField(default=datetime.time(0, 10), verbose_name='cleaning duration: ')),
                ('description', models.TextField(verbose_name='description')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to=settings.AUTH_USER_MODEL, verbose_name='instance created by')),
            ],
            options={
                'verbose_name': 'seance',
                'verbose_name_plural': 'seances',
                'ordering': ('time_starts',),
            },
        ),
        migrations.CreateModel(
            name='Seat',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveSmallIntegerField(default=0, verbose_name='number of seat')),
                ('row', models.PositiveSmallIntegerField(default=0, verbose_name='number of row')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to=settings.AUTH_USER_MODEL, verbose_name='instance created by')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='seance.Hall', verbose_name='hall')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_seance', models.DateField(default=datetime.date(2020, 6, 18), verbose_name='date of seance')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='instance created at')),
                ('was_returned', models.BooleanField(default=False, verbose_name='was_returned?')),
                ('purchase', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='seance.Purchase', verbose_name='purchase')),
                ('seance', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='seance.Seance', verbose_name='seance')),
                ('seat', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='tickets', to='seance.Seat', verbose_name='seat')),
            ],
        ),
        migrations.CreateModel(
            name='SeatCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20, verbose_name='category name')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='instance created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='instance updated at')),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_categories', to=settings.AUTH_USER_MODEL, verbose_name='instance created by')),
                ('price_list', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seat_categories', to='seance.PriceList', verbose_name='price list object')),
            ],
        ),
        migrations.AddField(
            model_name='seat',
            name='seat_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seats', to='seance.SeatCategory', verbose_name='seat category'),
        ),
        migrations.CreateModel(
            name='SeanceBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_starts', models.DateField(verbose_name='starts')),
                ('date_ends', models.DateField(blank=True, null=True, verbose_name='ends')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='instance created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='instance updated at')),
                ('is_active', models.BooleanField(default=True, verbose_name='in run?')),
                ('admin_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='creator: ')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='seance.Film', verbose_name='films')),
                ('hall', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='seance.Hall', verbose_name='hall')),
            ],
        ),
        migrations.AddField(
            model_name='seance',
            name='seance_base',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='seance.SeanceBase', verbose_name='base seance'),
        ),
    ]
