# Generated by Django 3.0.7 on 2020-06-19 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0002_auto_20200619_0757'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='film',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='hall',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='price',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterModelOptions(
            name='seatcategory',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.RemoveField(
            model_name='seancebase',
            name='is_active',
        ),
        migrations.AddField(
            model_name='seance',
            name='is_active',
            field=models.BooleanField(default=True, verbose_name='in run?'),
        ),
        migrations.AlterUniqueTogether(
            name='price',
            unique_together={('seance', 'seat_category')},
        ),
    ]
