# Generated by Django 3.0.7 on 2020-06-20 07:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0003_auto_20200619_1729'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='seancebase',
            options={'ordering': ('-updated_at',)},
        ),
        migrations.AlterField(
            model_name='hall',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='in run?'),
        ),
        migrations.AlterField(
            model_name='seance',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='in run?'),
        ),
        migrations.AlterField(
            model_name='seancebase',
            name='film',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='seances', to='seance.Film', verbose_name='film'),
        ),
    ]
