# Generated by Django 3.0.7 on 2020-06-20 13:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0004_auto_20200620_0705'),
    ]

    operations = [
        migrations.AddField(
            model_name='seance',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='instance created at'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='seance',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='instance updated at'),
        ),
    ]
