# Generated by Django 3.0.7 on 2020-06-21 06:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0005_auto_20200620_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seance',
            name='advertisements_duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 10), null=True, verbose_name='advertisements duration '),
        ),
        migrations.AlterField(
            model_name='seance',
            name='cleaning_duration',
            field=models.TimeField(blank=True, default=datetime.time(0, 10), null=True, verbose_name='cleaning duration '),
        ),
        migrations.AlterField(
            model_name='seance',
            name='time_ends',
            field=models.TimeField(blank=True, null=True, verbose_name='ends at '),
        ),
        migrations.AlterField(
            model_name='seance',
            name='time_hall_free',
            field=models.TimeField(blank=True, null=True, verbose_name='hall free at '),
        ),
        migrations.AlterField(
            model_name='seance',
            name='time_starts',
            field=models.TimeField(verbose_name='starts at '),
        ),
        migrations.AlterField(
            model_name='seat',
            name='hall',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seats', to='seance.Hall', verbose_name='hall'),
        ),
    ]
