# Generated by Django 3.0.7 on 2020-06-22 08:51

from django.db import migrations, models
import django.db.models.deletion
import seance.utilities


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0007_auto_20200622_0607'),
    ]

    operations = [
        migrations.AddField(
            model_name='film',
            name='image',
            field=models.ImageField(blank=True, upload_to=seance.utilities.get_timestamp_path, verbose_name='film picture'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='name',
            field=models.CharField(max_length=30, verbose_name='category name'),
        ),
        migrations.CreateModel(
            name='FilmAdditionalImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to=seance.utilities.get_timestamp_path, verbose_name='picture')),
                ('film', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='seance.Film', verbose_name='film')),
            ],
            options={
                'verbose_name': 'additional image',
                'verbose_name_plural': 'additional images',
            },
        ),
    ]
