# Generated by Django 3.0.7 on 2020-07-02 19:07

import colorfield.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seance', '0009_auto_20200627_0657'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hall',
            name='quantity_rows',
            field=models.PositiveSmallIntegerField(verbose_name='how many rows?'),
        ),
        migrations.AlterField(
            model_name='hall',
            name='quantity_seats',
            field=models.PositiveSmallIntegerField(verbose_name='how many seats?'),
        ),
        migrations.AlterField(
            model_name='seatcategory',
            name='color',
            field=colorfield.fields.ColorField(default='#FFFFFF', max_length=18),
        ),
    ]
